#!/usr/bin/env python3
"""
Generate a Qtile color module from the active pywal16 palette.

Reads:  ~/.cache/wal/colors.json
Writes: ~/.config/qtile/custom_utils/colors.py

The generated module exposes four names:

    background  - str   special.background (window background)
    foreground  - str   special.foreground (text, foreground)
    cursor      - str   accent color used for cursor-like highlights
    palette     - list  16 ANSI colors, indices 0..15 (color0..color15)

Usage in the Qtile config:

    from custom_utils.colors import background, foreground, cursor, palette

    widget.GroupBox(
        active=foreground,
        this_current_screen_border=palette[4],   # blue (color4)
        ...
    )

This file is overwritten on every theme change. Do not edit it by hand.
"""
import json
from pathlib import Path

CACHE_JSON = Path.home() / ".cache" / "wal" / "colors.json"
OUTPUT_PY  = Path.home() / ".config" / "qtile" / "custom_utils" / "colors.py"

# Cursor accent, taken from the palette by index.
# Index 2 = green (color2) — matches the cursor color Kvantum uses
# for Qt applications, keeping the whole environment visually consistent.
CURSOR_INDEX = 2

ANSI_LABELS = {
    0:  "black",
    1:  "red",
    2:  "green",
    3:  "yellow",
    4:  "blue",
    5:  "magenta",
    6:  "cyan",
    7:  "white",
    8:  "bright black",
    9:  "bright red",
    10: "bright green",
    11: "bright yellow",
    12: "bright blue",
    13: "bright magenta",
    14: "bright cyan",
    15: "bright white",
}


def load_palette() -> dict:
    if not CACHE_JSON.exists():
        raise SystemExit(f"pywal cache not found: {CACHE_JSON}")
    with open(CACHE_JSON) as f:
        return json.load(f)


def write_colors_py(wal: dict) -> None:
    special = wal["special"]
    colors  = wal["colors"]

    background = special["background"]
    foreground = special["foreground"]
    cursor     = colors.get(f"color{CURSOR_INDEX}", foreground)

    lines: list[str] = [
        "# AUTO-GENERATED by kc-themeflow/qtile_colors.py",
        "# Source: ~/.cache/wal/colors.json",
        "# Do not edit by hand — regenerated on every theme change.",
        "",
        f'background = "{background}"',
        f'foreground = "{foreground}"',
        f'cursor     = "{cursor}"',
        "",
        "# 16 ANSI colors, index 0..15 correspond to color0..color15",
        "palette = [",
    ]

    for i in range(16):
        hex_color = colors.get(f"color{i}", "#000000")
        label = ANSI_LABELS.get(i, "")
        lines.append(f'    "{hex_color}",  # {i:>2}  {label}')

    lines.append("]")
    lines.append("")

    OUTPUT_PY.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PY.write_text("\n".join(lines))
    print(f"Written: {OUTPUT_PY}")


def main() -> None:
    write_colors_py(load_palette())


if __name__ == "__main__":
    main()