#!/usr/bin/env python3
"""
Generate GTK 3 and GTK 4 stylesheets from the active pywal palette.

This replaces Gradience. Gradience was archived upstream in 2024, its
Flatpak is built against an unsupported runtime, and applying a preset
is a trivial file-generation task that does not require a sandboxed
application.

Inputs:
    ~/.cache/wal/pywal.json    — rendered by pywal from
                                 config/templates/pywal.json.
                                 Contains "variables" (named colors)
                                 and "palette" (numbered GTK shorthands).
    ~/.cache/wal/colors.json   — raw pywal palette, used for the
                                 treeview / row selection override.

Outputs:
    ~/.config/gtk-3.0/gtk.css
    ~/.config/gtk-4.0/gtk.css

Both files are overwritten on every run.
"""
import json
import sys
from pathlib import Path

CACHE_HOME = Path.home() / ".cache" / "wal"
CONFIG_HOME = Path.home() / ".config"

PYWAL_JSON = CACHE_HOME / "pywal.json"
COLORS_JSON = CACHE_HOME / "colors.json"

TARGETS = [
    (CONFIG_HOME / "gtk-3.0" / "gtk.css", "gtk3"),
    (CONFIG_HOME / "gtk-4.0" / "gtk.css", "gtk4"),
]


def load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def render_variables(variables: dict) -> str:
    return "\n".join(
        f"@define-color {key} {value};" for key, value in variables.items()
    )


def render_palette(palette: dict) -> str:
    lines = []
    for name, shades in palette.items():
        for index, value in shades.items():
            lines.append(f"@define-color {name}{index} {value};")
    return "\n".join(lines)


def render_selection(colors: dict, special: dict) -> str:
    bg = colors["color4"]
    fg = special["background"]
    return (
        "/* kc-themeflow: selection */\n"
        "treeview.view:selected,\n"
        "treeview.view:selected:focus,\n"
        "row:selected,\n"
        "row:selected:focus {\n"
        f"    background-color: {bg};\n"
        f"    color: {fg};\n"
        "}\n"
    )


def build_stylesheet(pywal: dict, colors: dict, custom_css: str) -> str:
    parts = [
        "/* Generated by kc-themeflow. Do not edit by hand. */",
        "",
        render_variables(pywal.get("variables", {})),
        "",
        render_palette(pywal.get("palette", {})),
        "",
        render_selection(colors["colors"], colors["special"]),
    ]
    if custom_css:
        parts += ["", custom_css.rstrip(), ""]
    return "\n".join(parts)


def main() -> None:
    if not PYWAL_JSON.is_file():
        print(f"error: {PYWAL_JSON} not found", file=sys.stderr)
        print("       is the pywal.json template deployed?", file=sys.stderr)
        sys.exit(1)
    if not COLORS_JSON.is_file():
        print(f"error: {COLORS_JSON} not found", file=sys.stderr)
        sys.exit(1)

    pywal = load_json(PYWAL_JSON)
    colors = load_json(COLORS_JSON)
    custom = pywal.get("custom_css", {})

    for target, key in TARGETS:
        content = build_stylesheet(pywal, colors, custom.get(key, "").strip())
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        print(f"Written: {target}")


if __name__ == "__main__":
    main()